/**
 * Honest content-freshness labels for data-driven pages.
 *
 * The date is a REAL signal — either an explicit per-record verification date, or
 * the data file's actual last-change date from git history (via sitemap-dates.ts,
 * regenerated by scripts/build-sitemap-dates.mjs). It is never a hardcoded/frozen
 * literal (that was the "Updated March 2026" anti-pattern we removed) and never
 * fabricated. "Updated" reflects when the data last changed; an explicit
 * `lastReviewed` upgrades the label to "Reviewed".
 */
import { sitemapDates, type SitemapDateKey } from '@/data/sitemap-dates'

const MONTHS = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
]

/** Format an ISO YYYY-MM-DD as "Month YYYY". Pure string math — deterministic, no timezone drift. */
export function formatMonthYear(iso?: string | null): string | null {
  if (!iso) return null
  const [y, m] = iso.split('-').map(Number)
  if (!y || !m || m < 1 || m > 12) return null
  return `${MONTHS[m - 1]} ${y}`
}

/**
 * Freshness stamp for a data group. Returns { label, date } or null when no honest
 * date exists. `explicit` (a record's lastReviewed) wins and reads "Reviewed";
 * otherwise falls back to the data file's git change date and reads "Updated".
 */
export function freshnessStamp(
  key: SitemapDateKey,
  explicit?: string
): { verb: 'Reviewed' | 'Updated'; date: string } | null {
  if (explicit) {
    const date = formatMonthYear(explicit)
    if (date) return { verb: 'Reviewed', date }
  }
  const date = formatMonthYear(sitemapDates[key])
  return date ? { verb: 'Updated', date } : null
}
