/**
 * Typed accessors + formatters for the "Where Rents Are Rising Fastest" dataset.
 * Source data is generated by scripts/build-fmr.mjs from HUD Fair Market Rents
 * (FY current vs prior), Two-Bedroom, 40th percentile.
 */
import nationalJson from './national.json'
import statesJson from './states.json'
import metrosJson from './metros.json'

export type FmrMeta = {
  curYear: number
  prevYear: number
  dataset: string
  source: string
  universe: string
  metric: string
  placeholder?: boolean
  generatedAt: string | null
  stateCount: number
  metroCount: number
}

export type GeoRent = {
  name: string
  slug: string
  abbr?: string
  state?: string | null
  code?: string
  fmr2br: number | null
  fmrPrev2br: number | null
  fmr1br?: number | null
  fmr3br?: number | null
  yoyPct: number | null
  metroCount?: number
}

export const fmrMeta = nationalJson.meta as FmrMeta
export const national = nationalJson as unknown as GeoRent & { meta: FmrMeta }
export const states = statesJson.states as GeoRent[]
export const metros = metrosJson.metros as GeoRent[]

/** True while the dataset is a committed placeholder (no live HUD pull yet). */
export const isPlaceholder = fmrMeta.placeholder === true

export function getStateBySlug(slug: string): GeoRent | undefined {
  return states.find((s) => s.slug === slug)
}
export function getMetroBySlug(slug: string): GeoRent | undefined {
  return metros.find((m) => m.slug === slug)
}

/** Rows with a defined YoY change, fastest-rising first. */
export const statesByGrowth = states.filter((s) => s.yoyPct != null)
export const metrosByGrowth = metros.filter((m) => m.yoyPct != null)

/** Metros where rent fell year-over-year, biggest drop first. */
export const metrosFalling = [...metrosByGrowth]
  .filter((m) => (m.yoyPct ?? 0) < 0)
  .sort((a, b) => (a.yoyPct ?? 0) - (b.yoyPct ?? 0))

export function stateRank(slug: string): number | null {
  const i = statesByGrowth.findIndex((s) => s.slug === slug)
  return i === -1 ? null : i + 1
}

// ── formatters ──────────────────────────────────────────────────────────────

/** $1,344 — whole-dollar rent. */
export function fmtRent(v: number | null | undefined): string {
  if (v == null) return '—'
  return `$${Math.round(v).toLocaleString('en-US')}`
}

/** +3.9% / −2.5% — signed year-over-year change (input is a fraction). */
export function fmtYoy(v: number | null | undefined, digits = 1): string {
  if (v == null) return '—'
  const pct = v * 100
  const sign = pct > 0 ? '+' : pct < 0 ? '−' : ''
  return `${sign}${Math.abs(pct).toFixed(digits)}%`
}

/** 3.9% — unsigned magnitude (for "rose X%" / "fell X%" prose). */
export function fmtYoyMag(v: number | null | undefined, digits = 1): string {
  if (v == null) return '—'
  return `${Math.abs(v * 100).toFixed(digits)}%`
}
