/**
 * Typed accessors + formatters for the Best Cash-Flow Markets (gross rental
 * yield) dataset. Source data is generated by scripts/build-rental-yield.mjs
 * from Census ACS 1-year estimates.
 */
import nationalJson from './national.json'
import statesJson from './states.json'
import metrosJson from './metros.json'

export type YieldMeta = {
  year: number
  dataset: string
  source: string
  universe: string
  metric: string
  placeholder?: boolean
  generatedAt: string | null
  stateCount: number
  metroCount: number
}

export type GeoYield = {
  name: string
  slug: string
  abbr?: string
  state?: string | null
  cbsa?: string
  medianGrossRent: number | null
  medianHomeValue: number | null
  grossYield: number | null
}

export const yieldMeta = nationalJson.meta as YieldMeta
export const national = nationalJson as unknown as GeoYield & { meta: YieldMeta }
export const states = statesJson.states as GeoYield[]
export const metros = metrosJson.metros as GeoYield[]

/** True while the dataset is the committed placeholder (no live ACS pull yet). */
export const isPlaceholder = yieldMeta.placeholder === true

export function getStateBySlug(slug: string): GeoYield | undefined {
  return states.find((s) => s.slug === slug)
}
export function getMetroBySlug(slug: string): GeoYield | undefined {
  return metros.find((m) => m.slug === slug)
}

/** Rows with a defined yield, highest first. */
export const statesByYield = states.filter((s) => s.grossYield != null)
export const metrosByYield = metros.filter((m) => m.grossYield != null)

export function stateRank(slug: string): number | null {
  const i = statesByYield.findIndex((s) => s.slug === slug)
  return i === -1 ? null : i + 1
}

// ---- formatters ----
export const fmtYield = (v: number | null, digits = 1) =>
  v == null ? '—' : `${(v * 100).toFixed(digits)}%`

export const fmtRent = (v: number | null) =>
  v == null ? '—' : `$${Math.round(v).toLocaleString('en-US')}/mo`

export function fmtValue(v: number | null): string {
  if (v == null) return '—'
  if (v >= 1e6) return `$${(v / 1e6).toFixed(2)}M`
  if (v >= 1e3) return `$${Math.round(v / 1e3)}K`
  return `$${v}`
}

export function ordinal(n: number): string {
  const s = ['th', 'st', 'nd', 'rd']
  const v = n % 100
  return n + (s[(v - 20) % 10] || s[v] || s[0])
}
