/**
 * Typed accessors + formatters for the "Most Active Investment-Property Lenders
 * by State" dataset, generated by scripts/build-hmda-lenders.mjs from the HMDA
 * combined Modified LAR. Ranked by HMDA-reported origination volume — a map of
 * the reported mortgage market, NOT a quality or "best lender" ranking.
 */
import nationalJson from './national.json'
import statesJson from './states.json'

export type LenderMeta = {
  year: number
  source: string
  universe: string
  generatedAt: string | null
  topPerState: number
  minOriginations: number
  distinctLenders: number
  nameResolution: { viaFilers: number; viaGleif: number; unresolved: number; of: number }
  nameNote: string
}

export type Lender = {
  rank: number
  lei: string
  name: string
  originations: number
  volume: number
  businessPurposeShare: number | null
  resolved: boolean
}

export type StateLenders = {
  abbr: string
  name: string
  slug: string
  totalInvestorOriginations: number
  lenders: Lender[]
}

export const lenderMeta = nationalJson.meta as LenderMeta
export const nationalLenders = nationalJson.lenders as Lender[]
export const nationalTotal = nationalJson.totalInvestorOriginations as number
export const states = statesJson.states as StateLenders[]

export function getStateBySlug(slug: string): StateLenders | undefined {
  return states.find((s) => s.slug === slug)
}

/** States ranked by total investor originations (largest market first). */
export const statesByVolume = [...states].sort(
  (a, b) => b.totalInvestorOriginations - a.totalInvestorOriginations
)

// ---- formatters (mirror the hmda-investor report) ----
export const fmtCount = (v: number) => v.toLocaleString('en-US')

export function fmtUSD(v: number): string {
  if (v >= 1e9) return `$${(v / 1e9).toFixed(1)}B`
  if (v >= 1e6) return `$${(v / 1e6).toFixed(0)}M`
  if (v >= 1e3) return `$${(v / 1e3).toFixed(0)}K`
  return `$${v}`
}

export const fmtPct = (v: number | null, digits = 0) =>
  v == null ? '—' : `${(v * 100).toFixed(digits)}%`

/** A lender is DSCR/business-purpose-oriented when most of its investor loans are business-purpose. */
export const lenderType = (l: Lender): 'DSCR / business-purpose' | 'Conventional' | 'Mixed' => {
  if (l.businessPurposeShare == null) return 'Mixed'
  if (l.businessPurposeShare >= 0.7) return 'DSCR / business-purpose'
  if (l.businessPurposeShare <= 0.2) return 'Conventional'
  return 'Mixed'
}

/** Compact label for charts: drop the legal suffix and cap length. */
export function shortName(name: string, max = 24): string {
  const trimmed = name
    .replace(/,?\s+(LLC|L\.L\.C\.|Inc\.?|INC\.?|LP|L\.P\.|LTD\.?|Corporation|Company|Co\.?|Trust|NA|N\.A\.|FSB)$/i, '')
    .trim()
  return trimmed.length > max ? `${trimmed.slice(0, max - 1)}…` : trimmed
}

export function ordinal(n: number): string {
  const s = ['th', 'st', 'nd', 'rd']
  const v = n % 100
  return n + (s[(v - 20) % 10] || s[v] || s[0])
}
