import { createClient } from '@sanity/client'

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID
const token = process.env.SANITY_API_WRITE_TOKEN

if (!projectId || !token) {
  console.error('Missing NEXT_PUBLIC_SANITY_PROJECT_ID or SANITY_API_WRITE_TOKEN in .env.local')
  console.error('Create a write token at: https://www.sanity.io/manage/project/' + (projectId || 'YOUR_PROJECT') + '/api#tokens')
  process.exit(1)
}

const client = createClient({
  projectId,
  dataset: 'production',
  apiVersion: '2026-03-12',
  token,
  useCdn: false,
})

// ── Author ────────────────────────────────────────────
const author = {
  _id: 'author-bill-rice',
  _type: 'author',
  name: 'Bill Rice',
  slug: { _type: 'slug', current: 'bill-rice' },
  bio: 'Real estate investor, strategist, and founder of ProInvestorHub. Helping investors make smarter decisions through education, data, and actionable tools.',
}

// ── Categories ────────────────────────────────────────
const categories = [
  { _id: 'cat-strategies', _type: 'category', title: 'Strategies', slug: { _type: 'slug', current: 'strategies' }, description: 'Investment strategies including BRRRR, house hacking, short-term rentals, fix-and-flip, and buy-and-hold.' },
  { _id: 'cat-analysis', _type: 'category', title: 'Deal Analysis', slug: { _type: 'slug', current: 'deal-analysis' }, description: 'How to analyze real estate deals, calculate returns, and evaluate risk.' },
  { _id: 'cat-financing', _type: 'category', title: 'Financing', slug: { _type: 'slug', current: 'financing' }, description: 'Mortgages, DSCR loans, hard money, creative financing, and funding strategies for investors.' },
  { _id: 'cat-beginner', _type: 'category', title: 'Getting Started', slug: { _type: 'slug', current: 'getting-started' }, description: 'Essential knowledge for new real estate investors taking their first steps.' },
  { _id: 'cat-tax', _type: 'category', title: 'Tax & Legal', slug: { _type: 'slug', current: 'tax-legal' }, description: '1031 exchanges, depreciation, entity structuring, and tax strategies for real estate investors.' },
  { _id: 'cat-markets', _type: 'category', title: 'Markets', slug: { _type: 'slug', current: 'markets' }, description: 'Market analysis, emerging markets, and geographic trends for real estate investors.' },
]

// ── Glossary Terms ────────────────────────────────────
const glossaryTerms = [
  {
    _type: 'glossaryTerm',
    term: 'Cap Rate',
    slug: { _type: 'slug', current: 'cap-rate' },
    definition: 'The capitalization rate is the ratio of a property\'s net operating income (NOI) to its purchase price or current market value, expressed as a percentage. It measures the expected rate of return on an investment property.',
    category: 'analysis',
    body: [
      { _type: 'block', _key: 'cr1', style: 'h2', children: [{ _type: 'span', _key: 'cr1s', text: 'How to Calculate Cap Rate' }] },
      { _type: 'block', _key: 'cr2', style: 'normal', children: [{ _type: 'span', _key: 'cr2s', text: 'Cap Rate = Net Operating Income (NOI) / Property Value × 100' }] },
      { _type: 'block', _key: 'cr3', style: 'normal', children: [{ _type: 'span', _key: 'cr3s', text: 'For example, if a property generates $30,000 in NOI annually and is valued at $400,000, the cap rate is 7.5% ($30,000 / $400,000 = 0.075).' }] },
      { _type: 'block', _key: 'cr4', style: 'h2', children: [{ _type: 'span', _key: 'cr4s', text: 'What is a Good Cap Rate?' }] },
      { _type: 'block', _key: 'cr5', style: 'normal', children: [{ _type: 'span', _key: 'cr5s', text: 'Cap rates vary by market, property type, and risk level. Generally, 4-6% is considered low-risk (Class A markets), 6-8% is moderate, and 8%+ indicates higher risk or emerging markets. The "right" cap rate depends on your investment goals and risk tolerance.' }] },
    ],
  },
  {
    _type: 'glossaryTerm',
    term: 'Net Operating Income (NOI)',
    slug: { _type: 'slug', current: 'noi' },
    definition: 'The total income generated by a property after deducting all operating expenses, but before deducting mortgage payments, capital expenditures, and income taxes.',
    category: 'analysis',
    body: [
      { _type: 'block', _key: 'n1', style: 'h2', children: [{ _type: 'span', _key: 'n1s', text: 'NOI Formula' }] },
      { _type: 'block', _key: 'n2', style: 'normal', children: [{ _type: 'span', _key: 'n2s', text: 'NOI = Gross Rental Income - Operating Expenses' }] },
      { _type: 'block', _key: 'n3', style: 'normal', children: [{ _type: 'span', _key: 'n3s', text: 'Operating expenses include property taxes, insurance, property management fees, maintenance, utilities (if owner-paid), and vacancy reserves. Mortgage payments are NOT included in operating expenses because NOI measures the property\'s performance independent of financing.' }] },
    ],
  },
  {
    _type: 'glossaryTerm',
    term: 'Cash-on-Cash Return',
    slug: { _type: 'slug', current: 'cash-on-cash-return' },
    definition: 'The ratio of annual pre-tax cash flow to the total cash invested in a property. Unlike cap rate, cash-on-cash return accounts for financing and measures the return on your actual out-of-pocket investment.',
    category: 'analysis',
  },
  {
    _type: 'glossaryTerm',
    term: 'BRRRR Method',
    slug: { _type: 'slug', current: 'brrrr-method' },
    definition: 'An investment strategy that stands for Buy, Rehab, Rent, Refinance, Repeat. Investors purchase undervalued properties, renovate them to increase value, rent them out, refinance to pull out their initial capital, and repeat the process.',
    category: 'strategies',
  },
  {
    _type: 'glossaryTerm',
    term: 'DSCR Loan',
    slug: { _type: 'slug', current: 'dscr-loan' },
    definition: 'A Debt Service Coverage Ratio loan is an investment property mortgage where qualification is based on the property\'s rental income rather than the borrower\'s personal income. Lenders typically require a DSCR of 1.0 or higher.',
    category: 'financing',
  },
  {
    _type: 'glossaryTerm',
    term: '1031 Exchange',
    slug: { _type: 'slug', current: '1031-exchange' },
    definition: 'A tax-deferred exchange under IRS Section 1031 that allows investors to sell an investment property and reinvest the proceeds into a "like-kind" property, deferring capital gains taxes.',
    category: 'tax',
  },
  {
    _type: 'glossaryTerm',
    term: 'Debt Service Coverage Ratio (DSCR)',
    slug: { _type: 'slug', current: 'dscr' },
    definition: 'The ratio of a property\'s net operating income to its total debt service (mortgage payments). A DSCR above 1.0 means the property generates enough income to cover its debt obligations.',
    category: 'financing',
  },
  {
    _type: 'glossaryTerm',
    term: 'Gross Rent Multiplier (GRM)',
    slug: { _type: 'slug', current: 'gross-rent-multiplier' },
    definition: 'A quick valuation metric calculated by dividing a property\'s price by its gross annual rental income. A lower GRM suggests a better investment, but it doesn\'t account for expenses.',
    category: 'analysis',
  },
  {
    _type: 'glossaryTerm',
    term: 'House Hacking',
    slug: { _type: 'slug', current: 'house-hacking' },
    definition: 'A strategy where an investor lives in one unit of a multi-family property (or rents out rooms in a single-family home) and rents out the remaining units to offset or eliminate their housing costs.',
    category: 'strategies',
  },
  {
    _type: 'glossaryTerm',
    term: 'Appreciation',
    slug: { _type: 'slug', current: 'appreciation' },
    definition: 'The increase in a property\'s value over time. Appreciation can be natural (driven by market forces) or forced (driven by improvements, renovations, or increased rental income).',
    category: 'general',
  },
  {
    _type: 'glossaryTerm',
    term: 'Cash Flow',
    slug: { _type: 'slug', current: 'cash-flow' },
    definition: 'The net amount of money remaining after all income is collected and all expenses (including mortgage payments) are paid. Positive cash flow means the property generates profit each month.',
    category: 'analysis',
  },
  {
    _type: 'glossaryTerm',
    term: 'Hard Money Loan',
    slug: { _type: 'slug', current: 'hard-money-loan' },
    definition: 'A short-term, asset-based loan from private lenders used primarily for fix-and-flip projects or bridge financing. Interest rates are higher than conventional loans but approval is faster and based on the property\'s value rather than borrower creditworthiness.',
    category: 'financing',
  },
  {
    _type: 'glossaryTerm',
    term: 'Vacancy Rate',
    slug: { _type: 'slug', current: 'vacancy-rate' },
    definition: 'The percentage of time a rental property is unoccupied during a given period. Investors typically budget 5-10% vacancy when analyzing deals to account for tenant turnover and unleased periods.',
    category: 'analysis',
  },
  {
    _type: 'glossaryTerm',
    term: 'Fix and Flip',
    slug: { _type: 'slug', current: 'fix-and-flip' },
    definition: 'An investment strategy where a property is purchased below market value, renovated to increase its value, and then sold for a profit. Success depends on accurate rehab cost estimates and after-repair value (ARV) projections.',
    category: 'strategies',
  },
  {
    _type: 'glossaryTerm',
    term: 'After Repair Value (ARV)',
    slug: { _type: 'slug', current: 'arv' },
    definition: 'The estimated market value of a property after all planned renovations and repairs are completed. ARV is critical for fix-and-flip investors and BRRRR strategy practitioners to determine maximum purchase price.',
    category: 'analysis',
  },
  {
    _type: 'glossaryTerm',
    term: 'Depreciation',
    slug: { _type: 'slug', current: 'depreciation' },
    definition: 'A tax deduction that allows property owners to deduct the cost of the building (not land) over its useful life — 27.5 years for residential and 39 years for commercial property. Depreciation reduces taxable income without requiring an actual cash outlay.',
    category: 'tax',
  },
  {
    _type: 'glossaryTerm',
    term: 'Equity',
    slug: { _type: 'slug', current: 'equity' },
    definition: 'The difference between a property\'s current market value and the outstanding mortgage balance. Equity increases through mortgage paydown, property appreciation, and forced appreciation from renovations.',
    category: 'general',
  },
  {
    _type: 'glossaryTerm',
    term: 'Short-Term Rental (STR)',
    slug: { _type: 'slug', current: 'short-term-rental' },
    definition: 'A property rented for brief periods, typically less than 30 days, often through platforms like Airbnb or VRBO. STRs can generate significantly higher income than long-term rentals but require more active management.',
    category: 'strategies',
  },
  {
    _type: 'glossaryTerm',
    term: 'Loan-to-Value Ratio (LTV)',
    slug: { _type: 'slug', current: 'ltv' },
    definition: 'The ratio of a mortgage loan amount to the appraised value of the property, expressed as a percentage. An 80% LTV means the borrower is financing 80% of the property\'s value and putting 20% down.',
    category: 'financing',
  },
  {
    _type: 'glossaryTerm',
    term: 'Internal Rate of Return (IRR)',
    slug: { _type: 'slug', current: 'irr' },
    definition: 'A metric that accounts for the time value of money to calculate the annualized return on an investment over its entire holding period, including cash flows, appreciation, and the eventual sale.',
    category: 'analysis',
  },
]

// ── Blog Posts ─────────────────────────────────────────
const posts = [
  {
    _type: 'post',
    title: 'Cap Rate Explained: The Most Important Number in Real Estate Investing',
    slug: { _type: 'slug', current: 'cap-rate-explained' },
    author: { _type: 'reference', _ref: 'author-bill-rice' },
    categories: [{ _type: 'reference', _ref: 'cat-analysis', _key: 'c1' }],
    publishedAt: '2026-03-12T10:00:00Z',
    excerpt: 'Cap rate is the first metric every investor learns — and the one most frequently misunderstood. Here\'s how to actually use it to compare deals and make better decisions.',
    seo: {
      metaTitle: 'Cap Rate Explained: What It Is, How to Calculate, and Why It Matters',
      metaDescription: 'Learn how to calculate capitalization rate, what makes a "good" cap rate, and how to use it to compare investment properties. Free guide with examples.',
    },
    body: [
      { _type: 'block', _key: 'p1b1', style: 'normal', children: [{ _type: 'span', _key: 'p1s1', text: 'If you\'re evaluating your first investment property — or your fiftieth — cap rate is likely the first number you\'ll look at. It\'s the single most common metric in real estate investing, and for good reason: it gives you a quick snapshot of a property\'s return potential.' }] },
      { _type: 'block', _key: 'p1b2', style: 'normal', children: [{ _type: 'span', _key: 'p1s2', text: 'But here\'s the problem: most investors use it wrong. They treat cap rate as the definitive measure of whether a deal is "good" or "bad," when it\'s really just the starting point of a much deeper analysis.' }] },
      { _type: 'block', _key: 'p1b3', style: 'h2', children: [{ _type: 'span', _key: 'p1s3', text: 'What Is Cap Rate?' }] },
      { _type: 'block', _key: 'p1b4', style: 'normal', children: [{ _type: 'span', _key: 'p1s4', text: 'Capitalization rate — or cap rate — is the ratio of a property\'s net operating income (NOI) to its purchase price or current market value. The formula is simple:' }] },
      { _type: 'block', _key: 'p1b5', style: 'blockquote', children: [{ _type: 'span', _key: 'p1s5', text: 'Cap Rate = Net Operating Income / Property Value × 100' }] },
      { _type: 'block', _key: 'p1b6', style: 'normal', children: [{ _type: 'span', _key: 'p1s6', text: 'For example, a property that generates $36,000 per year in NOI and is priced at $450,000 has a cap rate of 8% ($36,000 / $450,000 = 0.08).' }] },
      { _type: 'block', _key: 'p1b7', style: 'normal', children: [{ _type: 'span', _key: 'p1s7', text: 'Think of cap rate as the return you\'d earn if you bought the property in all cash. It strips out financing, giving you a clean way to compare properties regardless of how they\'re funded.' }] },
      { _type: 'block', _key: 'p1b8', style: 'h2', children: [{ _type: 'span', _key: 'p1s8', text: 'What Makes a "Good" Cap Rate?' }] },
      { _type: 'block', _key: 'p1b9', style: 'normal', children: [{ _type: 'span', _key: 'p1s9', text: 'This is where most beginners go wrong. There is no universal "good" cap rate. Cap rates reflect risk: higher cap rates generally mean higher risk (and potentially higher returns), while lower cap rates indicate lower risk (and lower returns).' }] },
      { _type: 'block', _key: 'p1b10', style: 'normal', children: [{ _type: 'span', _key: 'p1s10', text: 'A 4% cap rate in downtown San Francisco represents a very different risk profile than a 10% cap rate in a small Midwest town. Neither is inherently better — they serve different investment strategies.' }] },
      { _type: 'block', _key: 'p1b11', style: 'h2', children: [{ _type: 'span', _key: 'p1s11', text: 'Cap Rate vs. Cash-on-Cash Return' }] },
      { _type: 'block', _key: 'p1b12', style: 'normal', children: [{ _type: 'span', _key: 'p1s12', text: 'Cap rate measures unlevered return (as if you paid all cash). Cash-on-cash return measures the return on your actual cash invested, including the effects of financing. If you\'re using a mortgage, cash-on-cash return is the more relevant metric for evaluating your personal return.' }] },
      { _type: 'block', _key: 'p1b13', style: 'normal', children: [{ _type: 'span', _key: 'p1s13', text: 'Use cap rate to compare properties against each other. Use cash-on-cash return to evaluate how a deal performs for your specific financial situation.' }] },
      { _type: 'block', _key: 'p1b14', style: 'h2', children: [{ _type: 'span', _key: 'p1s14', text: 'When Cap Rate Doesn\'t Tell the Full Story' }] },
      { _type: 'block', _key: 'p1b15', style: 'normal', children: [{ _type: 'span', _key: 'p1s15', text: 'Cap rate is a snapshot metric. It doesn\'t account for appreciation potential, rent growth, capital expenditure needs, or the specific terms of your financing. A property with a lower cap rate in a high-growth market may outperform a higher cap rate deal in a stagnant market over a 5-10 year hold.' }] },
      { _type: 'block', _key: 'p1b16', style: 'normal', children: [{ _type: 'span', _key: 'p1s16', text: 'Always pair cap rate analysis with cash flow projections, market research, and a clear understanding of your investment timeline and goals.' }] },
    ],
  },
  {
    _type: 'post',
    title: '5 Real Estate Investing Strategies for Beginners in 2026',
    slug: { _type: 'slug', current: '5-real-estate-investing-strategies-beginners-2026' },
    author: { _type: 'reference', _ref: 'author-bill-rice' },
    categories: [
      { _type: 'reference', _ref: 'cat-beginner', _key: 'c1' },
      { _type: 'reference', _ref: 'cat-strategies', _key: 'c2' },
    ],
    publishedAt: '2026-03-10T10:00:00Z',
    excerpt: 'Getting started in real estate investing doesn\'t require millions of dollars. These five proven strategies let you start building wealth with whatever capital you have today.',
    seo: {
      metaTitle: '5 Best Real Estate Investing Strategies for Beginners (2026 Guide)',
      metaDescription: 'Discover the 5 best real estate investing strategies for beginners in 2026. From house hacking to BRRRR, learn which approach fits your budget and goals.',
    },
    body: [
      { _type: 'block', _key: 'p2b1', style: 'normal', children: [{ _type: 'span', _key: 'p2s1', text: 'The biggest myth in real estate investing is that you need a fortune to get started. The truth is, some of the most successful investors began with modest capital and a solid strategy. The key isn\'t how much money you have — it\'s choosing the right approach for your situation.' }] },
      { _type: 'block', _key: 'p2b2', style: 'h2', children: [{ _type: 'span', _key: 'p2s2', text: '1. House Hacking' }] },
      { _type: 'block', _key: 'p2b3', style: 'normal', children: [{ _type: 'span', _key: 'p2s3', text: 'House hacking is the single best entry point for new investors. The concept is simple: buy a multi-family property (duplex, triplex, or fourplex), live in one unit, and rent out the others. Your tenants effectively pay your mortgage, and you can qualify for owner-occupied financing with as little as 3.5% down through an FHA loan.' }] },
      { _type: 'block', _key: 'p2b4', style: 'normal', children: [{ _type: 'span', _key: 'p2s4', text: 'The beauty of house hacking is that it eliminates your largest expense (housing) while building equity and landlord experience simultaneously.' }] },
      { _type: 'block', _key: 'p2b5', style: 'h2', children: [{ _type: 'span', _key: 'p2s5', text: '2. Buy and Hold Rental Properties' }] },
      { _type: 'block', _key: 'p2b6', style: 'normal', children: [{ _type: 'span', _key: 'p2s6', text: 'The classic wealth-building strategy: purchase a property, rent it to tenants, and hold it long-term. You benefit from monthly cash flow, mortgage paydown by tenants, tax advantages through depreciation, and long-term appreciation. This strategy requires patience but has created more real estate millionaires than any other approach.' }] },
      { _type: 'block', _key: 'p2b7', style: 'h2', children: [{ _type: 'span', _key: 'p2s7', text: '3. The BRRRR Method' }] },
      { _type: 'block', _key: 'p2b8', style: 'normal', children: [{ _type: 'span', _key: 'p2s8', text: 'BRRRR stands for Buy, Rehab, Rent, Refinance, Repeat. You purchase a distressed property below market value, renovate it to force appreciation, rent it out, then refinance based on the new (higher) appraised value. If done correctly, you can pull out most or all of your initial investment and use that capital to buy the next property.' }] },
      { _type: 'block', _key: 'p2b9', style: 'normal', children: [{ _type: 'span', _key: 'p2s9', text: 'BRRRR is more advanced than house hacking, but it\'s the fastest way to scale a portfolio because you\'re recycling your capital with each deal.' }] },
      { _type: 'block', _key: 'p2b10', style: 'h2', children: [{ _type: 'span', _key: 'p2s10', text: '4. Short-Term Rentals (Airbnb/VRBO)' }] },
      { _type: 'block', _key: 'p2b11', style: 'normal', children: [{ _type: 'span', _key: 'p2s11', text: 'Short-term rentals can generate 2-3x the income of a traditional long-term rental in the right market. Platforms like Airbnb and VRBO have made it accessible for individual investors to compete in the hospitality space. The trade-off is significantly more management effort — guest communications, cleaning, furnishing, and local regulations.' }] },
      { _type: 'block', _key: 'p2b12', style: 'h2', children: [{ _type: 'span', _key: 'p2s12', text: '5. Real Estate Syndication' }] },
      { _type: 'block', _key: 'p2b13', style: 'normal', children: [{ _type: 'span', _key: 'p2s13', text: 'If you have capital but not time (or vice versa), syndications let you invest passively in larger deals. A sponsor handles the acquisition, management, and eventual sale, while limited partners contribute capital and receive returns. Minimum investments typically start at $25,000-$50,000.' }] },
      { _type: 'block', _key: 'p2b14', style: 'h2', children: [{ _type: 'span', _key: 'p2s14', text: 'Which Strategy Is Right for You?' }] },
      { _type: 'block', _key: 'p2b15', style: 'normal', children: [{ _type: 'span', _key: 'p2s15', text: 'Start with your constraints: How much capital do you have? How much time can you invest? What\'s your risk tolerance? House hacking is the lowest barrier to entry. Buy-and-hold is the most proven. BRRRR is the fastest path to scaling. STRs have the highest income potential. Syndications are the most passive. There\'s no wrong answer — only the right fit for your goals.' }] },
    ],
  },
]

// ── Site Settings ─────────────────────────────────────
const siteSettings = {
  _id: 'siteSettings',
  _type: 'siteSettings',
  title: 'ProInvestorHub',
  description: 'Expert education, free calculators, and in-depth guides for real estate investors. Make smarter investment decisions backed by data and knowledge.',
  footer: {
    tagline: 'Smart investing starts with better knowledge.',
    copyrightName: 'ProInvestorHub',
  },
}

// ── Run Seed ──────────────────────────────────────────
async function seed() {
  console.log('Seeding ProInvestorHub content...\n')

  const transaction = client.transaction()

  console.log('  + Author: Bill Rice')
  transaction.createOrReplace(author)

  for (const cat of categories) {
    console.log(`  + Category: ${cat.title}`)
    transaction.createOrReplace(cat)
  }

  for (const term of glossaryTerms) {
    console.log(`  + Glossary: ${term.term}`)
    transaction.create(term)
  }

  for (const post of posts) {
    console.log(`  + Post: ${post.title}`)
    transaction.create(post)
  }

  console.log('  + Site Settings')
  transaction.createOrReplace(siteSettings)

  console.log('\nCommitting...')
  const result = await transaction.commit()
  console.log(`Done! Created ${result.results.length} documents.`)
  console.log('\nYour content is now live. Visit http://localhost:3000 to see it!')
}

seed().catch((err) => {
  console.error('Seed failed:', err.message)
  process.exit(1)
})
