/**
 * Typed accessors + formatters for the HMDA Investor Financing Report dataset.
 * Source data is generated by scripts/build-hmda-investor.mjs from CFPB HMDA.
 */
import nationalJson from './national.json'
import statesJson from './states.json'

export type DenialReason = { reason: string; count: number }

export type InvestorFinancingRow = {
  abbr: string
  name: string
  slug: string
  investorOriginations: number
  investorVolume: number
  investorShare: number | null
  denialRate: number | null
  investorMedianRate: number | null
  ownerMedianRate: number | null
  ratePremiumBps: number | null
  investorMedianLtv: number | null
  businessPurposeShare: number | null
  cashOutShare: number | null
  topDenialReasons: DenialReason[]
  rateCoverage: number | null
}

export type ReportMeta = {
  year: number
  source: string
  universe: string
  generatedAt: string | null
  stateCount: number
}

export const reportMeta = nationalJson.meta as ReportMeta
export const national = nationalJson as unknown as InvestorFinancingRow & {
  meta: ReportMeta
}
export const states = statesJson.states as InvestorFinancingRow[]

export function getStateBySlug(slug: string): InvestorFinancingRow | undefined {
  return states.find((s) => s.slug === slug)
}

/** Numeric metric keys usable for ranking/coloring. */
export type MetricKey =
  | 'ratePremiumBps'
  | 'denialRate'
  | 'investorShare'
  | 'businessPurposeShare'
  | 'cashOutShare'
  | 'investorMedianLtv'
  | 'investorOriginations'

/** States ranked high→low by a metric (nulls dropped). 1 = highest value. */
export function rankedBy(metric: MetricKey): InvestorFinancingRow[] {
  return states
    .filter((s) => s[metric] != null)
    .sort((a, b) => (b[metric] as number) - (a[metric] as number))
}

/** A state's rank (1 = highest) among all states for a metric. */
export function rankOf(slug: string, metric: MetricKey): number | null {
  const ranked = rankedBy(metric)
  const i = ranked.findIndex((s) => s.slug === slug)
  return i === -1 ? null : i + 1
}

// ---- formatters ----
export const fmtPct = (v: number | null, digits = 1) =>
  v == null ? '—' : `${(v * 100).toFixed(digits)}%`

export const fmtBps = (v: number | null) => (v == null ? '—' : `${v} bps`)

export const fmtRate = (v: number | null) => (v == null ? '—' : `${v.toFixed(3).replace(/0+$/, '').replace(/\.$/, '')}%`)

export const fmtCount = (v: number) => v.toLocaleString('en-US')

export function fmtUSD(v: number): string {
  if (v >= 1e9) return `$${(v / 1e9).toFixed(1)}B`
  if (v >= 1e6) return `$${(v / 1e6).toFixed(0)}M`
  if (v >= 1e3) return `$${(v / 1e3).toFixed(0)}K`
  return `$${v}`
}

/** Ordinal suffix: 1 -> "1st". */
export function ordinal(n: number): string {
  const s = ['th', 'st', 'nd', 'rd']
  const v = n % 100
  return n + (s[(v - 20) % 10] || s[v] || s[0])
}
