/**
 * Typed accessors + formatters for the HMDA Investor Financing Report dataset.
 * Source data is generated by scripts/build-hmda-investor.mjs from CFPB HMDA.
 */
import nationalJson from './national.json'
import statesJson from './states.json'
import priorNationalJson from './national-2024.json'
import priorStatesJson from './states-2024.json'
import trendsJson from './trends.json'

export type DenialReason = { reason: string; count: number }

export type InvestorFinancingRow = {
  abbr: string
  name: string
  slug: string
  investorOriginations: number
  investorVolume: number
  investorShare: number | null
  denialRate: number | null
  investorMedianRate: number | null
  ownerMedianRate: number | null
  ratePremiumBps: number | null
  investorMedianLtv: number | null
  businessPurposeShare: number | null
  cashOutShare: number | null
  topDenialReasons: DenialReason[]
  rateCoverage: number | null
}

export type ReportMeta = {
  year: number
  source: string
  universe: string
  generatedAt: string | null
  stateCount: number
}

export const reportMeta = nationalJson.meta as ReportMeta
export const national = nationalJson as unknown as InvestorFinancingRow & {
  meta: ReportMeta
}
export const states = statesJson.states as InvestorFinancingRow[]

export function getStateBySlug(slug: string): InvestorFinancingRow | undefined {
  return states.find((s) => s.slug === slug)
}

/** Numeric metric keys usable for ranking/coloring. */
export type MetricKey =
  | 'ratePremiumBps'
  | 'denialRate'
  | 'investorShare'
  | 'businessPurposeShare'
  | 'cashOutShare'
  | 'investorMedianLtv'
  | 'investorOriginations'

/** States ranked high→low by a metric (nulls dropped). 1 = highest value. */
export function rankedBy(metric: MetricKey): InvestorFinancingRow[] {
  return states
    .filter((s) => s[metric] != null)
    .sort((a, b) => (b[metric] as number) - (a[metric] as number))
}

/** A state's rank (1 = highest) among all states for a metric. */
export function rankOf(slug: string, metric: MetricKey): number | null {
  const ranked = rankedBy(metric)
  const i = ranked.findIndex((s) => s.slug === slug)
  return i === -1 ? null : i + 1
}

// ---- formatters ----
export const fmtPct = (v: number | null, digits = 1) =>
  v == null ? '—' : `${(v * 100).toFixed(digits)}%`

export const fmtBps = (v: number | null) => (v == null ? '—' : `${v} bps`)

export const fmtRate = (v: number | null) => (v == null ? '—' : `${v.toFixed(3).replace(/0+$/, '').replace(/\.$/, '')}%`)

export const fmtCount = (v: number) => v.toLocaleString('en-US')

export function fmtUSD(v: number): string {
  if (v >= 1e9) return `$${(v / 1e9).toFixed(1)}B`
  if (v >= 1e6) return `$${(v / 1e6).toFixed(0)}M`
  if (v >= 1e3) return `$${(v / 1e3).toFixed(0)}K`
  return `$${v}`
}

/** Ordinal suffix: 1 -> "1st". */
export function ordinal(n: number): string {
  const s = ['th', 'st', 'nd', 'rd']
  const v = n % 100
  return n + (s[(v - 20) % 10] || s[v] || s[0])
}

// ---- year-over-year trend layer ----

/** A single metric's change between the prior and current year. */
export type Delta = {
  current: number | null
  prior: number | null
  abs: number | null
  pct: number | null
}

/** A state's value movement on one metric (used for "biggest movers"). */
export type Mover = {
  abbr: string
  name: string
  slug: string
  prior: number | null
  current: number | null
  abs: number | null
}

export type TrendsData = {
  meta: {
    currentYear: number
    priorYear: number
    currentSource: string
    priorSource: string | null
    note: string
    generatedAt: string | null
  }
  national: Record<string, Delta>
  states: Array<{ abbr: string; name: string; slug: string } & Record<string, Delta>>
  movers: Record<string, Mover[]>
}

export const trends = trendsJson as unknown as TrendsData
export const priorYear = trends.meta.priorYear
export const priorNational = priorNationalJson as unknown as InvestorFinancingRow & {
  meta: ReportMeta
}
export const statesPrior = priorStatesJson.states as InvestorFinancingRow[]

/** A state's prior-year row, by slug. */
export function getPriorStateBySlug(slug: string): InvestorFinancingRow | undefined {
  return statesPrior.find((s) => s.slug === slug)
}

/** A state's year-over-year delta row (per-metric Delta), by slug. */
export function getStateTrendBySlug(
  slug: string
): ({ abbr: string; name: string; slug: string } & Record<string, Delta>) | undefined {
  return trends.states.find((s) => s.slug === slug)
}

// ---- signed delta formatters ----

/** "+12 bps" / "-12 bps" / "—". */
export const fmtSignedBps = (v: number | null) =>
  v == null ? '—' : `${v > 0 ? '+' : ''}${v} bps`

/** Percentage-point change from a fractional delta: 0.035 -> "+3.5 pts". */
export const fmtSignedPts = (v: number | null, digits = 1) =>
  v == null ? '—' : `${v > 0 ? '+' : ''}${(v * 100).toFixed(digits)} pts`

/** Relative percent change: 0.165 -> "+16.5%". */
export const fmtPctChange = (v: number | null, digits = 1) =>
  v == null ? '—' : `${v > 0 ? '+' : ''}${(v * 100).toFixed(digits)}%`

/** Signed integer count: 74066 -> "+74,066". */
export const fmtSignedCount = (v: number | null) =>
  v == null ? '—' : `${v > 0 ? '+' : ''}${v.toLocaleString('en-US')}`

/** Direction of a delta for arrow/label rendering. */
export const trendDir = (v: number | null): 'up' | 'down' | 'flat' =>
  v == null || v === 0 ? 'flat' : v > 0 ? 'up' : 'down'

/** Count of states whose metric moved up / flat / down year over year. */
export function premiumDirectionCounts() {
  let up = 0,
    flat = 0,
    down = 0
  for (const s of trends.states) {
    const d = (s as Record<string, Delta>).ratePremiumBps?.abs
    if (d == null || d === 0) flat++
    else if (d > 0) up++
    else down++
  }
  return { up, flat, down }
}
