/**
 * Typed accessors + formatters for the American Rental Ownership Report.
 * Source data is generated by scripts/build-rhfs.mjs from the U.S. Census Bureau
 * Rental Housing Finance Survey (RHFS) Public Use Files (2018, 2021, 2024),
 * property-weighted by WEIGHT (unit estimates by WEIGHT × NUMUNITS_R).
 */
import nationalJson from './national.json'

export type RhfsMeta = {
  curYear: number
  prevYear: number
  waves: number[]
  dataset: string
  source: string
  universe: string
  metric: string
  note: string
  generatedAt: string | null
}

export type OwnEntity = {
  code: number
  label: string
  propShare: number | null
  unitShare: number | null
  propShareReported: number | null
  unitShareReported: number | null
}

export type SizeBand = {
  code: number
  label: string
  propShare: number | null
  unitShare: number | null
}

export type Wave = {
  year: number
  propertyTotal: number
  unitTotal: number
  nonreportedOwnershipShare: number | null
  entities: OwnEntity[]
  individual: { propShare: number | null; unitShare: number | null; propShareReported: number | null }
  llc: { propShare: number | null; unitShare: number | null; propShareReported: number | null }
  sizes: SizeBand[]
  financing: { debtPropShare: number | null; debtUnitShare: number | null }
  value: { medianMarketValue: number | null; medianPurchasePrice: number | null }
}

export type TrendPoint = {
  year: number
  individualPropShare: number | null
  llcPropShare: number | null
  individualUnitShare: number | null
  llcUnitShare: number | null
}

const data = nationalJson as unknown as {
  meta: RhfsMeta
  current: Wave
  previous: Wave
  byYear: Record<string, Wave>
  trend: TrendPoint[]
}

export const rhfsMeta = data.meta
export const current = data.current
export const previous = data.previous
export const byYear = data.byYear
export const trend = data.trend

/** Institutional = every ownership entity except the individual investor. */
export const institutionalPropShare2024 = round1(
  100 - (current.individual.propShare ?? 0) - (current.nonreportedOwnershipShare ?? 0)
)

/** 2024 ownership entities, largest property share first, dropping ~0 rows. */
export const entitiesByProp = [...current.entities]
  .filter((e) => (e.propShare ?? 0) >= 0.1)
  .sort((a, b) => (b.propShare ?? 0) - (a.propShare ?? 0))

/** 2024 ownership entities, largest UNIT share first. */
export const entitiesByUnit = [...current.entities]
  .filter((e) => (e.unitShare ?? 0) >= 0.1)
  .sort((a, b) => (b.unitShare ?? 0) - (a.unitShare ?? 0))

// ── formatters ──────────────────────────────────────────────────────────────

function round1(n: number): number {
  return Math.round(n * 10) / 10
}

/** 58.9% — a share already expressed in percent. */
export function fmtPct(v: number | null | undefined, digits = 1): string {
  if (v == null) return '—'
  return `${v.toFixed(digits)}%`
}

/** +5.2 pts / −12.7 pts — signed change between two percent shares. */
export function fmtPp(from: number | null | undefined, to: number | null | undefined, digits = 1): string {
  if (from == null || to == null) return '—'
  const d = to - from
  const sign = d > 0 ? '+' : d < 0 ? '−' : ''
  return `${sign}${Math.abs(d).toFixed(digits)} pts`
}

/** 19.0M — a large count rendered in millions. */
export function fmtMillions(v: number | null | undefined, digits = 1): string {
  if (v == null) return '—'
  return `${(v / 1_000_000).toFixed(digits)}M`
}

/** $275,000 — whole-dollar money. */
export function fmtMoney(v: number | null | undefined): string {
  if (v == null) return '—'
  return `$${Math.round(v).toLocaleString('en-US')}`
}
