// AUTO-GENERATED by scripts/build-sitemap-dates.mjs — do not edit by hand.
// Per route-group last-content-change dates (from git history) for sitemap <lastmod>.
// Regenerate after data/content changes: node scripts/build-sitemap-dates.mjs

export const sitemapDates = {
  "calculators": "2026-07-14",
  "calculatorsHub": "2026-06-13",
  "capRateCities": "2026-03-14",
  "categoryContent": "2026-03-26",
  "financingScenarios": "2026-06-11",
  "financingTypes": "2026-06-13",
  "home": "2026-04-03",
  "lenderComparisons": "2026-07-14",
  "lenders": "2026-06-25",
  "loanTypes": "2026-06-13",
  "marketStrategies": "2026-06-05",
  "reportInvestorFinancing": "2026-06-15",
  "reportInvestorLenders": "2026-06-18",
  "reportRentGrowth": "2026-06-23",
  "reportRentalOwnership": "2026-07-17",
  "reportRentalYield": "2026-06-17",
  "usStates": "2026-03-28"
} as const

export type SitemapDateKey = keyof typeof sitemapDates

/** Real last-change date for a group as a Date, or undefined if unknown (omit lastmod — never fabricate). */
export function groupLastmod(key: SitemapDateKey): Date | undefined {
  const d = sitemapDates[key]
  return d ? new Date(d + 'T00:00:00Z') : undefined
}
